###
# data sources
data_sources:
    casename: &casename
      gcp-cases
    path_to_cat_json: '/glade/u/home/eromashkova/codes/diag-sandbox/catalog/gcp-cases.json'
    subset:
      case:
        - 'g.e22.GOMIPECOIAF_JRA-1p4-2018.TL319_g17.GCB_2022.BCRC'
        - 'g.e22.GOMIPECOIAF_JRA-1p4-2018.TL319_g17.GCB_2022.BCRD'

###
# computation config keys
output_dir: ./_computed-notebooks/*casename
default_kernel_name: diag-sandbox
project: NCGD0011


###
# book table of contents
book_toc:
  format: jb-book
  root: description
#  parts:
#    - caption: Ocean Carbon Cycle
#      chapters:
#        - file: ocn-fgco2
#    - caption: Ocean Tracers
#      chapters:
#        - file: intro-ocn-tracer-views
#          sections:
#            - glob: ocn-tracer-views*

###
# book _config.yml keys
book_config_keys:
  title: My CESM Experiment
  repository:
    url: https://github.com/matt-long/my-cesm-experiment
    path_to_book: notebooks
    branch: main

###
# computational notebooks
compute_notebooks:  

  description:
    use_cluster: False
    parameter_groups:
      none:
        casename: *casename
  
  ssh:
    use_cluster: True
    subset:
      frequency: 'month_1'
      component: 'ocn'
      variable: 'SSH'
    parameter_groups:  
      none:
        casename: *casename
       
        
        
        
