###
# data sources
data_sources:
    casename: &casename
      gcp-cases
    path_to_cat_json: '/glade/u/home/eromashkova/codes/diag-sandbox/catalog/gcp-cases.json'
    subset:
      case:
        - 'g.e22.GOMIPECOIAF_JRA-1p4-2018.TL319_g17.GCB_2022.BCRC'
    cache_metadata_path: '/glade/u/home/eromashkova/codes/my-cesm-experiment-extended/notebooks/cache_metadata'
    cache_data_path: '/glade/u/home/eromashkova/codes/my-cesm-experiment-extended/notebooks/cache_data'

###
# computation config keys
output_root: ./_computed-notebooks
default_kernel_name: diag-sandbox
project: NCGD0011


###
# book table of contents
book_toc:
  format: jb-book
  root: description
  parts:
    - caption: Sea Surface Height
      chapters:
        - file: ssh
    - caption: MOC
      chapters:
        - glob: moc-view*

###
# book _config.yml keys
book_config_keys:
  title: My CESM Experiment
  repository:
    url: https://github.com/matt-long/my-cesm-experiment
    path_to_book: notebooks
    branch: main

###
# computational notebooks
compute_notebooks:  

  description:
    use_cluster: False
    parameter_groups:
      none:
        casename: *casename
  
  ssh:
    use_cluster: True
    subset:
      frequency: 'month_1'
      component: 'ocn'
      variable: 'SSH'
    parameter_groups:  
      none:
        casename: *casename

  POP_MOC_extract_cat:
    use_cluster: True
    kernel_name: diag-sandbox-moc-pop-tools
    subset:
      frequency: 'month_1'
      component: 'ocn'
      variable: 'MOC'
    parameter_groups:  
      none:
        casename: *casename
       
  moc-view:
    use_cluster: True
    kernel_name: diag-sandbox-moc-pop-tools
    dependency: 'POP_MOC_extract_cat'
    parameter_groups:
      26n:
        casename: *casename
        title_param: "26n"
        
        
        
